### PR TITLE
6to5 support

### PR DESCRIPTION
**Pull request by guybedford**
WIP

### CODE REVIEW

**Comment by theefer** [comment]
Exciting!

**Comment by guybedford** [comment]
This is now complete!

To use it - 

```html
<script src="system.js"></script>
<script>
  System.config({ parser: '6to5', to5Options: {parserOptions} });
  System.import('some-es6-file');
</script>
```

The default parser is Traceur. The above will look for `6to5.js` in the current folder of SystemJS just like we did for loading Traceur. 6to5 runtime is loaded automatically just like we loaded Traceur runtime (if being used - `to5Options.runtime` I think).

A custom path to 6to5 can be set on the script with an attribute:

```html
<script src="system.js" data-6to5-src="/my/custom/6to5.js"></script>
```

Which will then be loaded on-demand.

Any feedback on the above welcome.

**Comment by douglasduteil** [comment]
It's looking good. 
Did you drop the parser attachment on the polyfill  to load it from systemjs following https://github.com/systemjs/systemjs/issues/313 ?

**Comment by guybedford** [comment]
I just combined the parsers into the one build, it's not that much code - https://github.com/ModuleLoader/es6-module-loader/blob/6to5/src/parser.js.

**Comment by guybedford** [comment]
I just combined the parsers into the one build, it's not that much code - https://github.com/ModuleLoader/es6-module-loader/blob/6to5/src/parser.js.

**Comment by benib** [comment]
I'm am currently getting my feet wet with systemjs in combination with 6to5. now i wonder why this PR is closed. Will this get merged at some point? Is there any roadmap around about systemjs and 6to5 support?

**Pull request closed without merging**
