### PR TITLE
Update instantiate.js

### PR DESCRIPTION
**Pull request by kouts**
Replaced startsWith method with indexOf method for compatibility with IE11.

### CODE REVIEW

**Comment by thecriderman** [comment]
The method you have provided may scan the whole string and find a non-relevant index.

What are your thoughts on using slice to emulate startswith instead?

```javascript
source.slice(codeStart, codeStart + 17) === "SystemJS.register" || source.slice(codeStart, codeStart + 15) === "System.register"
```
Or even substr?
```javascript
source.substr(codeStart, 17) === "SystemJS.register" || source.substr(codeStart, 15) === "System.register"
```

**Comment by guybedford** [comment]
@kouts just let me know if you update the PR here - GitHub doesn't send notifications on new commits.

**Comment by kouts** [comment]
Thanks @guybedford , [PR](https://github.com/systemjs/systemjs/pull/1845/commits/49a7539a1cfdf51c5de7d102b46dfa7254c617af) updated.

**Comment by guybedford** [comment]
Thanks again @kouts for tracking this down.

**Comment by kouts** [comment]
Thanks for your work @guybedford

**Pull request merged**
