### PR TITLE
fix runtime issue when you make modules of restricted objects e.g. wi…

### PR DESCRIPTION
**Pull request by zeitiger**
…ndow object in a restricted browser

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, this bug should be avoided by the unreleased change in https://github.com/systemjs/systemjs/commit/a217ac0e64d881b7880c7a19d6863d338f4b5ef6 I believe though?

**Comment by zeitiger** [comment]
yes, that would also fix that bug. :+1: 
the indirect import $.global from core-js was root cause for me

**Comment by guybedford** [comment]
Ok thanks for confirming, I will close this for now then. If there are other bugs like this in future we can revisit the approach.

**Comment by zeitiger** [comment]
Short question, when did you plan to publish the next bugfix version that include your commit?

**Pull request closed without merging**
