### PR TITLE
importing systemjs in jest test fix

### PR DESCRIPTION
**Pull request by dara76**
- fix for https://github.com/systemjs/systemjs/issues/1055

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, I've added an alternative fix in https://github.com/systemjs/systemjs/commit/9a518551aa091303d8ed8f0dbe66bcfae2fbaa2f. Let me know if that works for you.

**Comment by dara76** [comment]
I gave your fix a go and the error still occurs. 

If I do `console.log(this.paths)` on the line before `this.paths = {}`, I see that `this.paths` is already defined there.

```
    this.map = {};
    console.log(this.paths); // outputs Object {}
    this.path = {};
```

**Comment by guybedford** [comment]
@dara76 I'm not too keen on this fix because `configNodePath` runs in the `SystemJSNodeLoader` constructor, which itself runs after the effective call to `super` on line 30 in index.js. So if `loader.paths` is undefined it would be good to know where and why it is undefined after running the constructor, rather than just patching it.

**Comment by dara76** [comment]
I understand your concern, I'll try to work out what's going on.

**Comment by dara76** [comment]
It turns out that jest is mocking the constructor, which presumably it shouldn't be given that I have `jest.autoMockOff();`.

In systemjs/index.js

```
var SystemJSLoader = require('./dist/system.src').constructor;  
console.log(SystemJSLoader);
// output is function SystemJSLoader() {return mockConstructor.apply(this,arguments);}
```

**Pull request closed without merging**
