### PR TITLE
String removal

### PR DESCRIPTION
**Pull request by guybedford**
@theefer I had another crack at your previous work and I think this resolves things!

Basically, to avoid string characters in regexs breaking things, we just needed to limit the string capture to be single-line only.

@dougwilson thanks for the tip on this one.

### CODE REVIEW

**Comment by theefer** [comment]
Great! :+1:

**Comment by guybedford** [comment]
There is one issue here though and that is the original issue still applies for minified sources. So one may test and have it work fine unminified, then minify separate files and have code break, which is perhaps not ideal - dev / production differences and all.

**Comment by theefer** [comment]
By minify do you mean bundling? Don't dependencies get statically
explicited in the register syntax?

**Comment by guybedford** [comment]
Yes bundling will statically convert the syntax, but if you were to leave separate files, but just minify the files separately (like we currently do on the CDN), then it would break.

The fix here is to always convert to System.register for separate file use. That's what I plan to enable with a SystemJS compile server for separate file production. Will send you the spec if you're interested.

**Comment by guybedford** [comment]
New PR at https://github.com/systemjs/systemjs/pull/726.

**Pull request closed without merging**
