### PR TITLE
Dynamic import maps

### LINKED ISSUE #2211: Dynamic import map updates
### Demonstration
https://codesandbox.io/s/systemjs-ignored-import-maps-j5xcl

### Expected Behavior
Be aware of updates to any import map for later use of `System.resolve()` (for `System.set()`).

### Actual Behavior
Only the first call to `System.prepareImport()` will parse import maps.

### Possible Solution
Use `MutationObserver` to pick up any changes to `script[type=systemjs-importmap]`, which might denecessitate `prepareImport()`.

### PR DESCRIPTION
**Pull request by stevenvachon**
Closes #2211

### CODE REVIEW

**Comment by stevenvachon** [comment]
The tests pass locally 🤷

**Comment by guybedford** [comment]
@stevenvachon thanks for the PR. I'm working on a refactoring to try and simplify the base - on the of the biggest things we need to focus on for the project is keeping the byte footprint down since it is so critical, so a lot of work needs to go into that here still. Were you able to test IE11?

**Comment by stevenvachon** [comment]
> ... keeping the byte footprint down since it is so critical, so a lot of work needs to go into that here still.

A lot of work on this PR?

> Were you able to test IE11?

No, but I can try and figure that out today.

**Comment by guybedford** [comment]
@stevenvachon would you mind if I pushed some commits here and rebase this to https://github.com/systemjs/systemjs/pull/2216?

**Comment by stevenvachon** [comment]
I don't mind. I'll create a contingency backup branch.

**Comment by guybedford** [comment]
Hmm, it seems git doesn't like doing this with the master branch... I'm now getting permission denied as the PR got closed.

If you want to reopen this PR we can try again to get the credit. Otherwise I will create a new one.

**Comment by stevenvachon** [comment]
I don't care about the credit.

**Comment by guybedford** [comment]
Released in 6.4.0.

**Comment by guybedford** [comment]
@stevenvachon I've confirmed this is working in IE11 in https://github.com/systemjs/systemjs/commit/42308a1f5ad5113cf01a4a4a36fa4eef754a17bc.

**Pull request closed without merging**
