### PR TITLE
Doc: packages meta path limitation

### PR DESCRIPTION
**Pull request by peteruithoven**
See: https://github.com/systemjs/systemjs/issues/700#issuecomment-131412203

### CODE REVIEW

**Comment by guybedford** [comment]
I see your point, but I think this would actually add more confusion.

**Comment by peteruithoven** [comment]
Because it's very short? 
Would it help if we added a link to a normalization information page where we add a small meta path chapter, so we have a bit more room for explanation but keep the info on the Configuration api page very concise.

**Comment by guybedford** [comment]
Yeah that would make sense.

**Comment by peteruithoven** [comment]
Alright then I'm closing this for now. I've added a comment to the normalization documentation page issue: https://github.com/systemjs/systemjs/issues/675#issuecomment-131754385

**Pull request closed without merging**
