### PR TITLE
disable `eval` for css files

### PR DESCRIPTION
**Pull request by nightnei**
`eval` for css files caught to error

### CODE REVIEW

**Comment by joeldenning** [comment]
This looks good to me. It could potentially break things if anyone is using the transform extra to convert CSS files into javascript modules, though. I don't think babel plugins usually do that, but am not sure about all the different transforms people are using beyond that. @guybedford can you comment on whether you think this will be breaking behavior for anyone?

**Comment by LarsDenBakker** [comment]
I expect people will use a babel plugin for transforming css files to polyfill css modules when/if they become a thing. When using babel CLI you can give a list of file extensions, perhaps that's a good approach here as well.

**Comment by guybedford** [comment]
This seems like justification again for the new transform hook model exposed in https://github.com/systemjs/systemjs/pull/2058, which allows inspecting the MIME type directly to decide what to transform within the fetch layer without needing this extra.

So given that will move forward eventually, I would consider the transform extra itself to be deprecated, as the model doesn't handle these complexities as well.

Whether we land is then just a question of how necessary this is for compatibility with workflows right now today for users.

**Comment by joeldenning** [comment]
I'm uncertain on whether / how to proceed on this one. @guybedford - thoughts ?

**Comment by guybedford** [comment]
The transform hook is now deprecated as of https://github.com/systemjs/systemjs/pull/2257.

**Pull request closed without merging**
