### PR TITLE
Added plugin-sass to README

### PR DESCRIPTION
**Pull request by screendriver**

### CODE REVIEW

**Comment by guybedford** [comment]
Sure, I'll gladly include this. Can you remove the build diff from the PR first?

**Comment by screendriver** [comment]
Hmm ok, how? I really did change anything. I only added the one line to the README and hit save in my editor: https://github.com/screendriver/systemjs/commit/f2e2b6daf8b352f83217577b166c9a893dac5922#diff-04c6e90faac2675aa89e2176d2eec7d8R137

**Comment by guybedford** [comment]
Yes I was meddling with the dist build commit, no problem I've merged this manually now.

**Comment by screendriver** [comment]
:+1:

**Pull request closed without merging**
