### PR TITLE
wildcard in bundles include the / boundaries

### LINKED ISSUE #1089: Bundle with wildcard and more than one directory level not working
**One directory level: Working**

Assume we have this directory structure: 
- package1/module1.js
- package1/module2.js

these modules get bundled into the following file: 
- package1.js

The config now looks like this: 

```
System.config({  
    "package1.js": ["package1/*"]
});
```

The loader loads the bundle file when accessing `package1/module1` or `package1/module2`. 

**Deeper directory level: Not working**

However, when the `package1` directory contains another directory, this does not work: 
- package1/module1.js
- package1/module2.js
- package1/directory/module2.js

Bundle: 
- package1.js

Config: 

```
System.config({  
    "package1.js": ["package1/*"]
});
```

Now, when loading the module `package1/directory/module3` it is not loaded from the bundle but loaded from the original location...

**Problem**

Is there a way to define a wildcard (`*`) that does also match directories but not only files (`/**/*` does not work either)?

### PR DESCRIPTION
**Pull request by tolemac**
If bundle has some wildcard convert the wildcard-bundle to a regexp and check if it's match.

Closes #1089

### CODE REVIEW

**Comment by tolemac** [comment]
@guybedford I have added some tests.
I hope lets good to you ;)

**Comment by guybedford** [comment]
@tolemac if we just accept a single wildcard, then the logic can be simplified to just check the start and end of the string. This is done for paths in https://github.com/systemjs/systemjs/blob/ee392b91a54cb2865d4aa10b1d2843eb501185d3/lib/paths.js#L22, something similar may reduce the diff here considerably.

**Comment by tolemac** [comment]
@guybedford, now we just accept a single wildcard ;)
I hope looks good to you ;)

**Comment by guybedford** [comment]
👍 thanks for your work here.

**Comment by tolemac** [comment]
To you,  for your support.

**Comment by CxRes** [comment]
@guybedford @tolemac Could you please document this? Currently the documentation categorically states no wildcards are allowed in SystemJS 0.20!!!!!

**Comment by tolemac** [comment]
Yes I agree. I'm doing an intensive use of that.
@guybedford I could make a PR of `docs/production-workflows.md` adding info about use of wildcard at [bundle extension](https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#bundle-extension) section.

Are you agree?

**Pull request merged**
