### PR TITLE
Fix right branch setting `load.metadata.deps`

### PR DESCRIPTION
**Pull request by crisptrutski**
@guybedford has the look of typo to me, but has been so for quite some time - thought I'd flag it

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, I don't think that right branch ever actually gets hit, but it should be `getCJSDeps(load.source)` for deps to concat.

**Comment by crisptrutski** [comment]
Figured unhit to not have caused issues. Not sure what you mean about deps, did you see `var deps = getCJSDeps(load.source);`? 

Maybe the best would be a short-and-sweet `load.metadata.deps = (load.metadata.deps || []).concat(getCJSDeps(load.source));` (why save cycles on the hypothetical ghost branch)

**Comment by guybedford** [comment]
load.metadata.deps must always concat with existing deps.

**Comment by guybedford** [comment]
I pulled this in with https://github.com/systemjs/systemjs/commit/b8e1ded1f2d94982c4c2c32aa5f885c23ee0e823.

**Pull request closed without merging**
