### PR TITLE
0.17 wip

### PR DESCRIPTION
**Pull request by guybedford**
* Tracks ES6 module loader 0.17 branch (https://github.com/ModuleLoader/es6-module-loader/pull/346)
* System.registerDynamic (https://github.com/systemjs/systemjs/issues/161)
* Removes versions extension
* Build no longer contains promises implementation
* New minimal production build
* Named imports from non-ES6 (https://github.com/systemjs/systemjs/issues/334)
* Global dependency shim layer like https://github.com/systemjs/systemjs/issues/148, but for all dynamic formats (except System.register) and using `meta.globals`.
* Support `metadata.plugin` as a plugin name
* `"deps jquery,bootstrap"` syntax now comma separated instead of additive
* wildcard meta support
* `format: 'es6'` is now `format: 'es'`
* Alias extension via metadata
* Package configurations
* CSP scriptLoading for AMD and System.register by default with meta hinting
* ~~Single default export loaded into CommonJS as entire value~~
* `format: 'register'` is now `format: 'system'`
* Conditional syntax support

### CODE REVIEW

**Comment by probins** [comment]
just so it doesn't get forgotten: if versions extension goes, there is a wiki page to go too

**Comment by szepeviktor** [comment]
@guybedford It this the PR which is called [rewrite](https://github.com/systemjs/systemjs/issues?q=is%3Aopen+is%3Aissue+label%3Arewrite)?

**Comment by guybedford** [comment]
@szepeviktor yes :)

**Comment by matthewp** [comment]
> Single default export loaded into CommonJS as entire value

Is this a good idea?  Won't that mean you get the same value with `import * as foo from "foo";` and `import foo from "foo"`?  This will cause refactor issues.

**Comment by matthewp** [comment]
> Alias extension via metadata

What is the advantage of aliases vs. a map?

**Comment by guybedford** [comment]
@matthewp it is specifically when loading into CommonJS that the default is taken. It doesn't change the ES6 import cases. The benefits of aliases is that they can have unique metadata, while referring to the same module source. The driving example is shimming Bootstrap.js to be dependent on loading its CSS via a deps metadata, not everyone wants that so we can do this via an alias.

**Comment by matthewp** [comment]
> it is specifically when loading into CommonJS that the default is taken.

I don't understand, isn't this what happens already?

### a

```
module.exports = function(){};
```

### b

```
var a = require("a");
```

This already gets the default, not the namespace. So I must be misunderstanding what you mean.

**Comment by matthewp** [comment]
Maybe you mean from es6 -> commonjs the default is taken?  I see the user-friendliness angle but this is still a refactor hazard.

**Comment by guybedford** [comment]
Yes exactly, we just make that work for loading ES6 from CommonJS against `export default function(){}`.

**Comment by guybedford** [comment]
Babel has implemented it and a lot of users ask for it.

**Comment by matthewp** [comment]
Do you know the issue of theirs? This is a bad idea.

**Comment by guybedford** [comment]
The interop section in http://babeljs.io/docs/usage/modules/.

**Comment by matthewp** [comment]
So this means if I refactor code from:

```js
export default function(){}
```

to

```js
export default function(){}

export function one(){}
```

All commonjs code consuming this module is broken, right?

**Comment by guybedford** [comment]
Yes, branching behaviour like this is certainly considered bad. I can certainly consider removing it, I'm just trying to go with the ecosystem though because behaviour changes between systems is going to be incredibly frustrating.

**Comment by matthewp** [comment]
Yeah, I understand the tradeoffs, but from a library authors perspective this isn't semver friendly. There will be a lot of accidental major version bumps caused.

Would you consider a way to turn the behavior off, as Babel does, a `System.commonStrict = true` perhaps?

**Comment by guybedford** [comment]
@matthewp let's continue discussion at https://github.com/systemjs/systemjs/issues/304. I think it's an implement or not here - don't want to add a conditional mode to SystemJS itself either.

**Pull request merged**
