### PR TITLE
Fix SystemJSLoader prototype constructor

### PR DESCRIPTION
**Pull request by katrotz**
Related issue: https://github.com/systemjs/systemjs/issues/786

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks! I guess we can remove https://github.com/systemjs/systemjs/blob/9bc693e4114b6d9cb36ac557f0f8a71ba68c7dcd/lib/createSystem.js#L2 then?

**Comment by guybedford** [comment]
Sorry I've been messing with the latest build diffs, do you think you can rebase again?

Commit updates don't notify - do ping me when you've updated this.

**Comment by katrotz** [comment]
@guybedford I've fixed the PR, thanks.

**Comment by guybedford** [comment]
Many thanks!

**Pull request merged**
